name: flutter_telegram_bot
description: "Telegram API package"
version: 0.0.24
homepage: https://github.com/mammadnihal/flutter_telegram_bot
repository: https://github.com/mammadnihal/flutter_telegram_bot
issue_tracker: https://github.com/mammadnihal/flutter_telegram_bot/issues
environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"
license: MIT

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
